version: "3.8"
services:
  app:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - nginx:/data
      - nginx-letsencrypt:/etc/letsencrypt

  pocketbase:
    platform: linux/arm64/v8
    image: awaddd/pocketbase:2.5
    command: /pb/pocketbase serve --http=0.0.0.0:8080
    ports:
      - 8080:8080
    volumes:
      - pocketbase-data:/pb/pb_data
      - pocketbase-migrations:/pb/pb_migrations

  strapi4:
    platform: linux/arm64/v8
    image: awaddd/strapi4:0.2
    command: npm run dev
    ports:
      - 1337:1337
    volumes:
      - strapi4:/strapi/.tmp

  chronicle:
    platform: linux/arm64/v8
    image: awaddd/chronicle:0.1-dev
    command: npm run start
    ports:
      - 3000:3000

volumes:
  nginx:
  nginx-letsencrypt:
  pocketbase-data:
  pocketbase-migrations:
  strapi4:
