services:
  pocketbase:
    platform: linux/arm64
    image: awaddd/pocketbase:2.2
    command: /pb/pocketbase serve --http=0.0.0.0:8080
    ports:
      - 8080:8080
    volumes:
      - pocketbase-data:/pb/pb_data
      - pocketbase-migrations:/pb/pb_migrations

  strapi3:
    platform: linux/arm64
    image: awaddd/strapi3:1.2
    command: npm run dev
    ports:
      - 127.0.0.1:1337:1337
    volumes:
      - strapi3:/strapi/.tmp

volumes:
  pocketbase-data:
  pocketbase-migrations:
  strapi3:
